language: c
sudo: false
compiler: gcc
dist: trusty
before_install:
  - pip install cpp-coveralls
addons:
  coverity_scan:
    project:
      name: "jluebbe/rauc"
      description: "Robust Auto-Update Controller"
    notification_email: jluebbe@lasnet.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: master
  apt:
    packages:
      - autoconf
      - automake
      - libglib2.0-dev
      - libjson-glib-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - squashfs-tools
      - lcov
      - slirp
      - user-mode-linux
      - grub-common
script:
  - ./autogen.sh
  - ./configure --enable-code-coverage
  - make clean
  - make -j2
  - make check TESTS= && ./uml-test
  - make distcheck
after_success:
  - coveralls --build-root '.' --exclude tests --exclude rauc-installer-generated.c
after_failure:
  - cat test/*.log
