#group: deprecated-2017Q2
filter_secrets: false
language: c
sudo: required
compiler: gcc
dist: trusty
#env:
#  global:
#     - DISPLAY=99:0
#    - DBUS_SESSION_BUS_ADDRESS=/dev/null
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/
    trusty main restricted universe multiverse" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake libglib2.0-dev libjson-glib-dev
    libssl-dev libcurl4-openssl-dev squashfs-tools dosfstools lcov slirp python-sphinx
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/
    vivid main restricted universe multiverse" -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq user-mode-linux grub-common
  - sudo pip install cpp-coveralls
  - echo $DBUS_SESSION_BUS_ADDRESS
  - unset DISPLAY
addons:
  coverity_scan:
    project:
      name: "jluebbe/rauc"
      description: "Robust Auto-Update Controller"
    notification_email: jluebbe@lasnet.de
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: master
script:
  - ./autogen.sh
  - ./configure --enable-code-coverage
  - make clean
  - make -j2
  - make doc SPHINXOPTS=-W
  - make check TESTS= && sudo ./uml-test
  - make distcheck
after_success:
  - coveralls --build-root '.' --exclude tests --exclude rauc-installer-generated.c
after_failure:
  - for i in $(find . -name rauc.log); do cat $i; done
  #- cat test/*.log
