env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
  - secure: "fBX9BSPK40ilGx/yxT6YphQFc1kD5e4Lu4WF/vAx+OgnxZKhGRHyjeQBsQoZpkwj4rcReiYBphdRxuQmRncLOdjIpJng+X2gYJynKLXF98VCqxCW0RDoTRFOnKZ7oEO/zYxT+5+a6q/0xRyPfJATmHpHrD9gM/FKg2Tc6Y2CpbEZ3EZY3vGzliE+CQIeZ/7XICSMwT6d/45x9bX7pizy50i5I2xpl270QCwuXOqocECDuwLGR6Q+cS0Wi5TedSbOrmzdm68TtKJbA0Kqkgdvg0CyAwpMOTLuYjqtuDxmijhV42v2CIA61gWEkFCz3aiJV3rHBLAkxrLFW1RH+uLvD825lYQD4iIuxz8YbyWEMyFWxMa7L4D6pnL2S93uK0oC9ReASkctUzgediVik5iK1rhJxJpKm8BM0xx9FaQXM0GVNUQWRL9Qxe7ZSooRGZG2tiAWB+gU6v7fKKM0apB38y+vXi2iZirfQJA11ucfCB0AcfzZhC0OYPH/7k9wvtbk01YBBcb5m7QMyK9V2KoC4deq0VLJBKCYsWZZOZkylXygv5SpXQKCwkDYLvGsSUtC88KQRAlm3N2Ox9hhAsgkZutb0MgKymKZM+czdRyQYvT2pcxG+HAiBZttetgFGZo7x44aVDlyX8jgbwGvTN2fKkvsBO8BJGY0pWQzAvqb0Uk="


language: c
sudo: required
compiler: gcc-7
dist: xenial
before_install:
  echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - sudo pip install --upgrade cpp-coveralls
  # travis-ci/travis-ci#9037: remove mongodb because the repository key is expired and we don't need it
  - sudo rm -fv /etc/apt/sources.list.d/mongodb*
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -q
  - sudo apt-cache policy gcc-7
  - sudo apt-get install -q gcc-7
  - sudo add-apt-repository --yes 'deb http://deb.debian.org/debian/ buster main'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553 7638D0442B90D010 04EE7237B7D453EC
  - sudo apt-get update -q
  - sudo apt-get install -q casync
  # work around https://bugs.launchpad.net/ubuntu/+source/libp11/+bug/1690287
  - sudo ln -s /usr/lib/ssl/engines/libpkcs11.so /usr/lib/x86_64-linux-gnu/openssl-1.0.0/engines/libpkcs11.so
addons:
  apt:
    packages:
      - autoconf
      - automake
      - libglib2.0-dev
      - libjson-glib-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - squashfs-tools
      - dosfstools
      - lcov
      - slirp
      - python-sphinx
      - dbus-x11
      - user-mode-linux
      - grub-common
      - softhsm2
      - opensc
      - opensc-pkcs11
      - libengine-pkcs11-openssl
      - faketime
    sources: &sources
      - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse'
  coverity_scan:
    project:
      name: "ejoerns/rauc"
      description: "Robust Auto-Update Controller"
    notification_email: ejo@pengutronix.de
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-7 --template && ./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: coverity_scan
before_script:
  - ./build-uncrustify.sh
script:
  - cat /home/travis/build/rauc/rauc/cov-int/build-log.txt | true
  - cat /home/travis/build/rauc/rauc/cov-int/scm_log.txt | true
  - ./autogen.sh
  - ./configure --enable-code-coverage
  - make clean
  - make -j2
  - make doc SPHINXOPTS=-W
  - make check TESTS= && sudo ./uml-test
  - make distcheck
  - cd contrib/cgi/
  - ./autogen.sh
  - ./configure
  - make clean
  - make -j2
  - make distcheck
  - cd ../..
  - ./uncrustify.sh && git diff --exit-code
after_success:
  - coveralls --build-root '.' --exclude test --exclude rauc-installer-generated.c
after_failure:
  - cat test/*.log
  - cat test-suite.log
