name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rauc/rauc/rauc-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev
    env:
      LOOPDEV_DEBUG: all
    steps:
    - name: Inspect environment
      run: |
        whoami
        gcc --version
        mount --version
        uname -a
        lsmod

    - name: Install something
      run: |
        echo "deb http://deb.debian.org/debian/ testing main" > /etc/apt/sources.list.d/testing.list
        apt-get update
        #DEBIAN_FRONTEND='noninteractive' apt-get install -qy software-properties-common
        #add-apt-repository deb http://deb.debian.org/debian/ testing main
        DEBIAN_FRONTEND='noninteractive' apt-get install -qy util-linux

    - name: Re-Inspect environment
      run: |
        mount --version

    - uses: actions/checkout@v2

    - name: Run test.sh
      run: |
        for run in {1..20}; do ./test/test.sh; done

    - name: Run autogen.sh
      run: |
        ./autogen.sh

    - name: Run distcheck
      run: |
        ./configure --enable-code-coverage --enable-gpt CFLAGS=-Werror
        make -j4 distcheck

    - name: Build CGI example
      run: |
        cd contrib/cgi
        ./autogen.sh
        ./configure CFLAGS=-Werror
        make clean
        make -j4
        make -j4 distcheck

    - name: Show system status
      run: |
        dmesg | tail -n 100
        mount || true
        losetup || true
        dmsetup table || true
        dmsetup targets || true

    - name: Show logs
      if: ${{ failure() }}
      run: |
        cat config.log || true
        cat test/*.log || true
        cat test-suite.log || true
        cat rauc-*/_build/sub/test-suite.log || true
        dmesg | tail -n 100
