name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rauc/testing:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev
    steps:
    - name: Inspect environment
      run: |
        whoami
        gcc --version

    - uses: actions/checkout@v2

    - name: Run autogen.sh
      run: |
        ./autogen.sh

    - name: Test with service and gpt
      run: |
        ./configure --enable-code-coverage --enable-gpt CFLAGS=-Werror
        make clean
        make -j4
        make -j4 check TESTS=
        ./qemu-test
        lcov --directory . --capture --output-file "service.info"
        
    - name: Test without service and gpt
      run: |
        ./configure --enable-code-coverage --disable-service CFLAGS=-Werror
        make clean
        make -j4
        make -j4 check TESTS=
        ./qemu-test
        lcov --directory . --capture --output-file "noservice.info"

    - name: Show system status
      if: ${{ failure() }}
      run: |
        dmesg | tail -n 100
        mount || true
        losetup || true
        dmsetup table || true
        dmsetup targets || true

    - name: Show logs
      if: ${{ failure() }}
      run: |
        cat config.log || true
        cat test/*.log || true
        cat test-suite.log || true
        cat rauc-*/_build/sub/test-suite.log || true
        dmesg | tail -n 100
