name: tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rauc/rauc/rauc-ci:latest
      # allow mounting and devtmpfs in the container
      options: --user=root --privileged -v /dev:/dev
    env:
      G_MESSAGES_DEBUG: "rauc rauc-subprocess"
    steps:
    - name: Inspect environment
      run: |
        whoami
        gcc --version
        mount --version
        uname -a
        lsmod

    - name: Install something
      run: |
        #echo "deb http://deb.debian.org/debian/ testing main" > /etc/apt/sources.list.d/testing.list
        apt-get update
        echo "deb http://de.archive.ubuntu.com/ubuntu/ hirsute-updates main" > /etc/apt/sources.list.d/hirsute.list
        apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 871920D1991BC93C
        apt-get update
        #DEBIAN_FRONTEND='noninteractive' apt-get install -qy software-properties-common
        #add-apt-repository deb http://de.archive.ubuntu.com/ubuntu hirsute-updates main
        DEBIAN_FRONTEND='noninteractive' apt-get install -qy util-linux lsof
        # killing in the name of..
        ps faux

    - name: Re-Inspect environment
      run: |
        mount --version

    - uses: actions/checkout@v2

      #- name: Run test.sh
      #  run: |
      #    ./test/test.sh 50

    - name: Run autogen.sh
      run: |
        ./autogen.sh

    - name: Run distcheck
      run: |
        ./configure --enable-code-coverage --enable-gpt CFLAGS=-Werror
        udevadm monitor > udev.log &
        make -j4 check

    - name: Show system status
      if: ${{ failure() }}
      run: |
        dmesg | tail -n 100
        mount || true
        losetup || true
        dmsetup table || true
        dmsetup targets || true

    - name: Show logs
      if: ${{ failure() }}
      run: |
        cat config.log || true
        cat test/*.log || true
        cat test-suite.log || true
        cat rauc-*/_build/sub/test-suite.log || true
        cat udev.log || true
        dmesg | tail -n 100
